

server-website: "https://skyeden.org/"
dynmap: "livemap.skyeden.org"
discord: "https://discord.gg/5Ja3Kkw"
donations: "https://www.skyeden.org/donations"
information: "info.skyeden.org"
forester: "https://www.skyeden.org/forester-application"
applications: "https://www.skyeden.org/staff-application"
pmc-website: "apply.skyeden.org"
runes: "runes.skyeden.org"
news: "news.skyeden.org"
